try {


  // did an error occur?
  return false
}
catch (errorDuringTurn) {
  console.log(errorDuringTurn);
  return errorDuringTurn;
}